archviz_house:
  camera:
    top: {"x": -12.394, "y": 3.6, "z": -5.06}
    left: {"x": -14.84, "y": 1.3, "z": -5.06}
    right: {"x": -9.948, "y": 1.3, "z": -5.06}
    front: {"x": -12.394, "y": 1.3, "z": -7.506}
    back: {"x": -12.394, "y": 1.3, "z": -2.614}
    look_at: {"x": -12.394, "y": 1.2, "z": -5.06}
  #xyz
  object:
    center: [-12.394, 1.2, -5.06]
    top: [-12.394, 1.2, -4.0816]
    right: [-11.394, 1.2, -5.06]
    bottom: [-12.394, 1.2, -6.04]
    left: [-13.394, 1.2, -5.06]
  vision_boundary: {'x': [-13.394, -11.394], 'z': [-6.04, -4.0816], 'y': 1.2}

empty_scene:
  camera:
    top: {"x": 0, "z": 0, "y": 7.5}
    left: {"x": -2.5, "z": 0, "y": 5.2}
    right: {"x": 2.5, "z": 0, "y": 5.2}
    front: {"x": 0, "z": -2.5, "y": 5.2}
    back: {"x": 0, "z": 2.5, "y": 5.2}
    look_at: {"x": 0, "y": 0.1, "z": 0}
  object:
    center: [0,5.1,0]
    top: [0,5.1,1]
    right: [1,5.1,0]
    bottom: [0,5.1,-1]
    left: [-1,5.1,0]
  vision_boundary: {'x': [-1, 1], 'z': [-1, 1], 'y': 5.1}
  
box_room_2018:
  camera:
    top: {"x": 0, "z": 0, "y": 2.5}
    left: {"x": -2.5, "z": 0, "y": 0.2}
    right: {"x": 2.5, "z": 0, "y": 0.2}
    front: {"x": 0, "z": -2.5, "y": 0.2}
    back: {"x": 0, "z": 2.5, "y": 0.2}
    look_at: {"x": 0, "y": 0, "z": 0}
  object:
    center: [0,0.1,0]
    top: [0,0.1,1]
    right: [1,0.1,0]
    bottom: [0,0.1,-1]
    left: [-1,0.1,0]
  vision_boundary: {'x': [-1, 1], 'z': [-1, 1], 'y': 0.1}

monkey_physics_room:
  camera:
    top: {"x": 0, "z": 0, "y": 2.5}
    left: {"x": -2.5, "z": 0, "y": 0.25}
    right: {"x": 2.5, "z": 0, "y": 0.25}
    front: {"x": 0, "z": -2.5, "y": 0.25}
    back: {"x": 0, "z": 2.5, "y": 0.25}
    look_at: {"x": 0, "y": 0.15, "z": 0}
  object:
    center: [0,0.15,0]
    top: [0,0.15,1]
    right: [1,0.15,0]
    bottom: [0,0.15,-1]
    left: [-1,0.15,0]
  vision_boundary: {'x': [-1, 1], 'z': [-1, 1], 'y': 0.15}

ruin:
  camera:
    top: {"x": -1.5, "z": -1.00, "y": 2.5}
    left: {"x": -4, "z": -1.00, "y": 0.2}
    right: {"x": 1, "z": -1.00, "y": 0.2}
    front: {"x": -1.5, "z": -3.5, "y": 1.2} #FAKE FRONT
    back: {"x": -1.5, "z": 1.5, "y": 0.2}
    look_at: {"x": -1.5, "y": 0.1, "z": -1.00}
  object:
    center: [-1.5,0.1,-1.00]
    top: [-1.5,0.1,0]
    right: [-0.5,0.1,-1.00]
    bottom: [-1.5,0.1,-2.00]
    left: [-2.5,0.1,-1.00]
  vision_boundary: {'x': [-2.5, -0.5], 'z': [-2, 0], 'y': 0.1}

suburb_scene_2018:
  camera:
    top: {"x": 0, "z": 0, "y": 2.5}
    left: {"x": -2.5, "z": 0, "y": 0.2}
    right: {"x": 2.5, "z": 0, "y": 0.2}
    front: {"x": 0, "z": -2.5, "y": 0.2}
    back: {"x": 0, "z": 2.5, "y": 0.2}
    look_at: {"x": 0, "y": 0.1, "z": 0}
  object:
    center: [0,0.1,0]
    top: [0,0.1,1]
    right: [1,0.1,0]
    bottom: [0,0.1,-1]
    left: [-1,0.1,0]
  vision_boundary: {'x': [-1, 1], 'z': [-1, 1], 'y': 0.1}