name: object_interaction
output_path: testbed11
port: 1075
display: :5
screen_size: [512, 512]
physics: false
render_quality: 10
library: models_special.json
scene: tdw_room # floorplan_2b, empty_scene box_room_2018 archviz_house mm_kitchen_2a tdw_room